# 01. Data Collection and Cleaning

This notebook loads the food delivery dataset and performs the cleaning steps from the original `models.ipynb`.

**Dataset path:** `../dataset/foodtimedataset.csv`

## 1. Import libraries

In [2]:
import pandas as pd
import numpy as np

## 2. Load the dataset

In [3]:
df = pd.read_csv("../dataset/foodtimedataset.csv")

df["Vehicle Type"] = df["Vehicle Type"].str.strip().str.title()

print(df["Vehicle Type"].unique())

print("Original shape:", df.shape)
df.head()

['Motorcycle' 'Scooter' 'Electric Scooter' 'Bicycle' nan]
Original shape: (10001, 17)

,ID,Delivery Person ID,Delivery Person Age,Delivery Person Ratings,Restaurant Latitude,Restaurant Longitude,Delivery Location Latitude,Delivery Location Longitude,Order Type,Vehicle Type,Temperature,Humidity,Precipitation,Weather Description,Traffic Level,Distance,Delivery Time
0,4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,Snack,Motorcycle,17.11,77.0,0.0,haze,Low,NaN,21.66666667
1,B379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,Snack,Scooter,19.50,93.0,0.0,mist,Very High,37.17,85.26666667
2,5D6D,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,Drinks,Motorcycle,20.45,91.0,0.0,mist,Low,3.34,28.58333333
3,7A6A,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,Buffet,Motorcycle,23.86,78.0,0.0,mist,Moderate,10.05,35.18333333
4,70A2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,Snack,Scooter,26.55,87.0,0.0,mist,High,9.89,43.45

## 3. Clean the dataset

- Remove spaces from column names and text values.
- Convert `Delivery Time` to numeric.
- Remove rows where delivery time is missing or not positive.

In [4]:
df.columns = df.columns.str.strip()

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

df["Delivery Time"] = pd.to_numeric(df["Delivery Time"], errors="coerce")
df = df.dropna(subset=["Delivery Time"])
df = df[df["Delivery Time"] > 0]

print("Cleaned shape:", df.shape)
df.head()

Cleaned shape: (9040, 17)

,ID,Delivery Person ID,Delivery Person Age,Delivery Person Ratings,Restaurant Latitude,Restaurant Longitude,Delivery Location Latitude,Delivery Location Longitude,Order Type,Vehicle Type,Temperature,Humidity,Precipitation,Weather Description,Traffic Level,Distance,Delivery Time
0,4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,Snack,Motorcycle,17.11,77.0,0.0,haze,Low,NaN,21.666667
1,B379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,Snack,Scooter,19.50,93.0,0.0,mist,Very High,37.17,85.266667
2,5D6D,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,Drinks,Motorcycle,20.45,91.0,0.0,mist,Low,3.34,28.583333
3,7A6A,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,Buffet,Motorcycle,23.86,78.0,0.0,mist,Moderate,10.05,35.183333
4,70A2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,Snack,Scooter,26.55,87.0,0.0,mist,High,9.89,43.450000

## 4. Check missing values and duplicates

In [5]:
print("Missing values by column:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Missing values by column:
ID                             0
Delivery Person ID             0
Delivery Person Age            0
Delivery Person Ratings        0
Restaurant Latitude            0
Restaurant Longitude           0
Delivery Location Latitude     0
Delivery Location Longitude    0
Order Type                     0
Vehicle Type                   0
Temperature                    0
Humidity                       0
Precipitation                  0
Weather Description            0
Traffic Level                  0
Distance                       5
Delivery Time                  0
dtype: int64

Duplicate rows: 0

## 5. Save the cleaned dataset (optional)

In [6]:
import os

os.makedirs("../dataset", exist_ok=True)
df.to_csv("../dataset/cleaned_foodtimedataset.csv", index=False)
print("Cleaned dataset saved to dataset/cleaned_foodtimedataset.csv")

Cleaned dataset saved to dataset/cleaned_foodtimedataset.csv